name: first code check

on:
  push:

jobs:
  first_check:
    name: first code check / python-${{ matrix.python-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Python info
        run: |
          which python
          python --version
      - name: Run unit tests
        run: |
          pip install pytest
          pytest
  
